version: '3.3'

services:
  app:
    build: .
    container_name: container_read_tickets
    ports:
      - 3100:3000
    networks:
      - local
    tty: true
    stdin_open: true
networks:
  local:
